### ISSUE TITLE
회원가입 및 로그인, 로그아웃 기능 구현

### ISSUE THREAD

**Issue by jiooong** [cheating-cheating-bank/backend#3]
## **Description**

- Spring security를 사용하여 회원가입, 로그인, 로그아웃 기능 구현하기

## **Todo**

- [ ]  User 엔티티
- [ ]  회원가입 기능 구현 및 회원 권한 부여
- [ ]  로그인 기능 구현
- [ ]  로그아웃 기능 구현
- [ ]  테스트 코드 작성하기
